[package]
name = "code-snippet"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
reqwest = { version = "0.12.15", features = ["json"] }
serde_json = "1.0.140"
